---
#-----------------------------------------
# Site settings
#-----------------------------------------
_merge: deep

title: Hugo Aurora
languageCode: en-gb

pagination:
  pagerSize: 3
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
enableInlineShortcodes: true
pygmentsUseClasses: true
pygmentsCodefences: true

#-----------------------------------------
# Params settings
#-----------------------------------------
params:
  author:
    firstName: Aurora
    lastName: Borealis
  description: An example site showcasing the Aurora Hugo theme.
  social:
    github: '#'
    gitlab: '#'
    linkedin: '#'
    instagram: '#'
    facebook: '#'
    twitter: '#'
    stackoverflow: '#'
    email: '#'
  analytics:
    enabled: false
    goatCounter:
      code: aurora

#-----------------------------------------
# Module settings
#-----------------------------------------
module:
  replacements: 'github.com/nszilard/aurora -> ../..'
  imports:
    - path: github.com/nszilard/aurora
